# Generated by Django 2.1.4 on 2019-01-20 06:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_archivo_empleado'),
    ]

    operations = [
        migrations.AddField(
            model_name='empleado',
            name='expediente',
            field=models.BooleanField(default=False),
        ),
    ]
